### ISSUE TITLE
libcblas.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by khumarahn** [sporkus/probe_accuracy_tests#8]
Hey. I'm installing the script following the manual, and then it refuses to run with
```
pi@v2:~ $ python3 ~/probe_accuracy_tests/probe_accuracy_test_suite.py 
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory
...
```

**Comment by khumarahn** [comment]
`apt install libatlas3-base` solves it, so this is not a real problem. But maybe add it to dependencies?

**Comment by sporkus** [comment]
> `apt install libatlas3-base` solves it, so this is not a real problem. But maybe add it to dependencies?

thanks! added to the install script https://github.com/sporkus/probe_accuracy_tests/commit/eb951d007cf65eb97901512d7b50ab71813702cc
